apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
  - namespace.yaml
patches:
  - path: patch-env-var.yaml
    target:
      kind: Deployment
replicas:
  - name: service-a
    count: 2
  - name: service-b
    count: 2
